# Generated by Django 5.2.6 on 2025-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AnonymFeedback',
                'verbose_name_plural': 'AnonymFeedback',
            },
        ),
        migrations.CreateModel(
            name='IdentifiedFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=100)),
                ('telegram_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'IdentifiedFeedback',
                'verbose_name_plural': 'IdentifiedFeedback',
            },
        ),
        migrations.AlterModelOptions(
            name='telegramusers',
            options={'verbose_name': 'School Users', 'verbose_name_plural': 'School Users'},
        ),
    ]
