# Generated by Django 5.2.6 on 2025-09-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_anonymfeedbackmodel_identifiedfeedbackmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymfeedbackmodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='identifiedfeedbackmodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
