# Generated by Django 5.2.6 on 2025-09-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_anonymfeedbackmodel_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymfeedbackmodel',
            name='telegram_id',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
