# Generated by Django 5.2.6 on 2025-09-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_anonymfeedbackmodel_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymfeedbackmodel',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
    ]
