# Generated by Django 5.2.6 on 2025-09-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_anonymfeedbackmodel_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymfeedbackmodel',
            options={'verbose_name': 'Anonym Feedback', 'verbose_name_plural': 'Anonym Feedback'},
        ),
        migrations.AlterModelOptions(
            name='identifiedfeedbackmodel',
            options={'verbose_name': 'Identified Feedback', 'verbose_name_plural': 'Identified Feedback'},
        ),
        migrations.AlterField(
            model_name='identifiedfeedbackmodel',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
    ]
